### ISSUE TITLE
Remove copyrighted content

### ISSUE THREAD

**Issue by anthonyhumphreys** [IamManchanda/algorithms-javascript#14]
https://www.udemy.com/coding-interview-bootcamp-algorithms-and-data-structure/

Stolen content !== open source

Not cool...

**Comment by IamManchanda** [comment]
I have given appropriate credit (See readme) ... Have tagged @StephenGrider in tweets also ... I don't think I did anything wrong, I was working on this more then a month after that ... I will pass on this issue

**Comment by IamManchanda** [comment]
Secondly this is forked from https://github.com/StephenGrider/AlgoCasts
which is available like this as open code... please don't make this a big deal

I haven't stolen any code

**Comment by IamManchanda** [comment]
I have gone ahead and added the credit of the fork in readme! https://github.com/IamManchanda/algorithms-javascript/commit/f3518450e8d738bda08c484edf627810b062bbda
Honestly speaking @antwan2093 I am deeply hurt by your issue because I was working on this from last 2 months and plan to work more (as you can see in readme about upcoming). This really hurts me after the hard work I have done towards this project. Attaching my certificate that I received after completion of course as a attachment also. This is not stolen code (It is the learned code) to my best of knowledge!
 
![algo-ds](https://user-images.githubusercontent.com/4970624/44284194-65a9b580-a27e-11e8-8718-597310e2b409.jpg)

**Comment by anthonyhumphreys** [comment]
Thanks for updating the repo. Unfortunately it is very common to see, especially on Reddit. Maybe being more open and upfront when you created and shared the repo would alleviated people’s concerns. As it stands, thanks for sharing :)
